@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title UC08 - Refugee chooces a language

class Refugee {
    id
    firstName
    lastName
    email
    gender
    photoURL
    mainLanguage
    mainPhoneNumber
    protocolId
    snsNumber
    nationality
    country
}

class Language {
}

Refugee "1   " - "   *" Language : selects >

@enduml