@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Register a Service Provider on the application

autonumber

actor ServiceProvider
participant ":RegisterProfessionalUI" as ui
participant ":RegisterProfessionalController" as ctrl
participant Repositories
participant "professionalRepo : ProfessionalRepository" as professionalRepo

activate ServiceProvider

    ServiceProvider -> ui : starts the process of registering a new Service Provider
    activate ui
        ui -> ctrl** : create()
        ui -> ctrl : registerServiceProvider()
        activate ctrl
            ctrl -> Repositories : getRefugeeRepository()
            activate Repositories
                Repositories -> Repositories : professionalRepository()
                Repositories-->ctrl : professionalRepo
            deactivate Repositories
        deactivate ctrl
            ui --> ServiceProvider : requests data (provided data*)
            ServiceProvider -> ui : fills requested data (provided data*)
        activate ctrl
            ui -> ctrl : createProfessional(provided data*)
            activate professionalRepo
                professionalRepo -> professionalRepo : localValidation(provided data*)
                professionalRepo --> professionalRepo : professional
            deactivate professionalRepo
            ctrl --> ui : success
        deactivate ctrl
    deactivate ui
deactivate ServiceProvider

note left of "professionalRepo : ProfessionalRepository"
    *Provided data*
    - First name
    - Last name
    - Gender
    - Main phone number
    - Email address
    - Address (Street name, door number, postal code and city name)
    - NIF
    - Main language
    - Second language
    - License Number
    - Category
    - Bank account information (Bank name, IBAN, Bank account holder name)
end note

@enduml