@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US013 - Service Provider checks his reviews

autonumber

actor ServiceProvider
participant ":System" as System

activate ServiceProvider
    ServiceProvider -> System : starts the process of requesting a reviews report.
    activate System
        System --> ServiceProvider : requests data (service provider id).
    deactivate System
    ServiceProvider -> System : fills request data (service provider id)
    activate System
        System --> ServiceProvider : displays a list with all reviews
    deactivate System
deactivate ServiceProvider

@enduml