@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US013 - Service Provider checks his reviews

autonumber

actor ServiceProvider
participant ":System" as System

activate ServiceProvider
    ServiceProvider -> System : starts the process of requesting a reviews report.
    activate System
        System --> ServiceProvider : asks for the options to filter and sort reviews based on different criteria, such as date, rating, or type of service of the reviews the professional wants to see.
    deactivate System
    ServiceProvider -> System : fills different criteria available
    activate System
        System --> ServiceProvider : validates and asks for confirmation
    deactivate System
    ServiceProvider -> System : confirms
    activate System
        System --> ServiceProvider : Shows reports with the information and notifies the success of the operation
    deactivate System
deactivate ServiceProvider

@enduml