@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US017 - Service Provider Requests admin for a new service type

autonumber

actor ServiceProvider
participant ":System" as System



@enduml