@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UC04 - Search for a service by location and its name (SSD)

autonumber

actor Refugee
participant ":System" as System

activate Refugee
    Refugee -> System : starts the process of searching for a specific service on a specific location
    activate System
        System --> Refugee : requests the description of searched service and a city name
    deactivate System

    Refugee -> System : fills requested data
    activate System
        System --> Refugee : shows all the services providers according to the chosen service description and city name
    deactivate System

    Refugee -> System : selects the desired service provider to see more information about him
    activate System
        System --> Refugee : shows detailed information
    deactivate System
deactivate Refugee
@enduml