@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title US024 - Service Provider manages his services

class Service {
    Id
    Name
    Category
}

class ServiceCategory {
    Id
    Name
}


class ServiceProvider {
    Id
    First Name
    Last Name
    License Number
    Address
    Phone Number
    Email
    Category
}



ServiceProvider " *   " - "   *" Service : has >
Service " *   " - "   1" ServiceCategory : has a >

@enduml