@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - UC09  Refugee chooses a language



autonumber

actor Refugee as refugee
participant ":System" as system

activate refugee
    refugee -> system : starts the process of selecting the language
    activate system
        system --> refugee : displays the list of the available languages
    refugee -> system : selects a language
    system --> refugee : translates the information according to the selected language
    deactivate system
deactivate refugee


@enduml