version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gladlyGiven
      POSTGRES_PASSWORD: upskill
      POSTGRES_DB: gladlyGiven
