@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UC08 - Design Model - Refugee chooses a language

actor Refugee as refugee
participant ":RefugeeUI" as ui
participant ":RefugeeController" as ctrl
participant "LanguageService" as languageService
participant "TranslationService" as translationService

activate refugee
    refugee -> ui : initiates language selection
    activate ui
        ui -> ctrl : getLanguages()
    deactivate ui
    activate ctrl
        ctrl -> languageService : getLanguages()
        activate languageService
            languageService -> languageService : retrieve languages
            languageService --> ctrl : languages
        deactivate languageService
        ctrl --> ui : languages
    deactivate ctrl
    activate ui
        ui --> refugee : displays language selection options
    deactivate ui
    refugee -> ui : selects language
    activate ui
        ui -> ctrl : translatePage(language)
        activate ctrl
            ctrl -> translationService : translatePage(language)
            activate translationService
                translationService -> translationService : translate page content
                translationService --> ctrl : translated content
            deactivate translationService
            ctrl --> ui : translated content
        deactivate ctrl
        ui --> refugee : translated content
    deactivate ui
deactivate refugee

@enduml