@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title UC05 - Service Provider visualize a list of services available

class ServiceProvider {
   id
   firstName
   lastName
   email
   gender
   mainLanguage
   secondLanguage
   mainPhoneNumber
   nif
   paymentInfoId
   invoiceInfoId
   licenseNumber
   categoryId
}

class HealthService {
    id
    description
    category
}

ServiceProvider "1   " - "   *" HealthService : views >

@enduml