@startuml
'https://plantuml.com/use-case-diagram

left to right direction
'top to bottom direction
title Gladly Given - Use Case Diagram

actor "Refugee" as Ref
actor "Donor" as Don
actor "ServiceProvider" as Pro
actor "Administrator" as Adm

usecase "UC01 - Register Refugee on the application" as UC01
usecase "UC02 - Register a Service Provider on the application" as UC02
usecase "UC03 - Register a Donor on the application" as UC03
usecase "UC04 - Search for a service by location and it's name" as UC04
usecase "UC05 - Service Provider visualizes a list of services available" as UC05
usecase "UC06 - Refugee schedules an appointment" as UC06
usecase "UC07 - Refugee evaluates the service provider" as UC07
usecase "UC08 - Refugee chooses a language" as UC08
usecase "UC09 - Display a FAQ page" as UC09
usecase "UC010 - User asks a question to administrator" as UC010
usecase "UC011 - Service Provider registers offered services " as UC011
usecase "UC012 - Service provider registers date and tiem for scheduling" as UC012
usecase "UC013 - Service Provider checks his reviews" as UC013
usecase "UC014 - Service provider requests service-related cost support" as UC014
usecase "UC015 - Donor makes a donation" as UC015
usecase "UC016 - Administrator displays the donation report" as UC016
usecase "UC017 - Service Provider requests admin for a new service" as UC017
usecase "UC018 - Refugee cancels or reschedules an appointment" as UC018
usecase "UC019 - Donor views a list of donations" as UC019
usecase "UC020 - Admin validates the request for service-related cost support" as UC020
usecase "UC021 - Service Provider views a list of his cost support requests" as UC021
usecase "UC022 - Service Provider views a list of hisnew service inclusion requests" as UC022
usecase "UC023 - Admin validates the request for a new service" as UC023



Ref -down-> UC01
Pro -down-> UC02
Don -down-> UC03
Ref -down-> UC04
Pro -down-> UC05
Ref -down-> UC06
Ref -down-> UC07
Ref -down-> UC08
Adm -down-> UC09
Ref -down-> UC010
Pro -down-> UC010
Pro -down-> UC011
Pro -down-> UC012
Pro -down-> UC013
Pro -down-> UC014
Don -down-> UC015
Don -down-> UC016
Pro -down-> UC017
Ref -down-> UC018
Don -down-> UC019
Adm -down-> UC020
Pro -down-> UC021
Pro -down-> UC022
Adm -down-> UC023

@enduml