@startuml
'https://plantuml.com/use-case-diagram

left to right direction
'top to bottom direction
title Gladly Given - Use Case Diagram

actor "Refugee" as Ref
actor "Donor" as Don
actor "ServiceProvider" as Pro
actor "Administrator" as Adm

usecase "UC01 - Register Refugee on the application" as UC01
usecase "UC02 - Register a Service Provider on the application" as UC02
usecase "UC03 - Register a Donor on the application" as UC03
usecase "UC04 - Search for a service by location and it's name" as UC04
usecase "UC05 - Search for a specific professional" as UC05
usecase "UC06 - Service Provider visualizes a list of services available" as UC06
usecase "UC07 - Refugee schedules an appointment" as UC07
usecase "UC08 - Refugee evaluates the service provider" as UC08
usecase "UC09 - Refugee chooses a language" as UC09
usecase "UC010 - Display a FAQ page" as UC010
usecase "UC011 - User asks a question to administrator" as UC011
usecase "UC012 - Service Provider updates offered services " as UC012
usecase "UC013 - Service provider registers his availability" as UC013
usecase "UC014 - Service Provider checks his reviews" as UC014
usecase "UC015 - Service provider requests service-related cost support" as UC015
usecase "UC016 - Donor makes a donation" as UC016
usecase "UC017 - Administrator displays the donation report" as UC017
usecase "UC018 - Service Provider requests admin for a new service" as UC018
usecase "UC019 - Refugee cancels or reschedules an appointment" as UC019
usecase "UC020 - Donor views a list of donations" as UC020
usecase "UC021 - Admin validates the request for service-related cost support" as UC021
usecase "UC022 - Service Provider views a list of his requests (cost support and new service)" as UC022
usecase "UC023 - Admin validates the request for a new service" as UC023



Ref -down-> UC01
Pro -down-> UC02
Don -down-> UC03
Ref -down-> UC04
Ref -down-> UC05
Pro -down-> UC06
Ref -down-> UC07
Ref -down-> UC08
Ref -down-> UC09
Adm -down-> UC010
Don -down-> UC011
Pro -down-> UC011
Ref -down-> UC011
Pro -down-> UC012
Pro -down-> UC013
Pro -down-> UC014
Pro -down-> UC015
Don -down-> UC016
Adm -down-> UC017
Pro -down-> UC018
Ref -down-> UC019
Don -down-> UC020
Adm -down-> UC021
Pro -down-> UC022
Adm -down-> UC023

@enduml