@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UC04 - Search for a service by location and its name

autonumber

actor Refugee
participant ":SearchServiceUI" as ui
participant ":SearchServiceController" as ctrl
participant Repositories
participant "serviceProviderRepo : ServiceProviderRepository" as serviceProviderRepo
participant "healthServiceRepo : HealthServiceRepository" as serviceRepo

activate Refugee
    Refugee -> ui : initiates search for a service by location and type of service
    activate ui
        ui --> Refugee : requests data (service description and city name)
    deactivate ui
    Refugee -> ui : fills requested data
    activate ui
        ui -> ctrl** : search(serviceDescription, cityName)
        activate ctrl
            ctrl -> Repositories : getHealthServiceRepository()
            activate Repositories
                Repositories -> Repositories : healthServiceRepository()
                Repositories --> ctrl : healthServiceRepo
            deactivate Repositories
            ctrl -> serviceRepo : findServiceByServiceDescription(serviceDescription)
        deactivate ctrl
        activate serviceRepo
            serviceRepo -> serviceRepo : findServiceByServiceDescription(serviceDescription)
            serviceRepo --> ctrl : service
        deactivate serviceRepo
        activate ctrl
            ctrl -> Repositories : getServiceProviderRepo()
        deactivate ctrl
        activate Repositories
                Repositories -> Repositories : serviceProviderRepository()
                Repositories --> ctrl : serviceProviderRepo
        deactivate Repositories
        activate ctrl
            ctrl -> serviceProviderRepo : findServiceProviderByServiceDescriptionAndCityName(serviceDescription, cityName)
            activate serviceProviderRepo
                serviceProviderRepo -> serviceProviderRepo : findServiceProviderByServiceDescriptionAndCityName(serviceDescription, cityName)
                serviceProviderRepo --> serviceProviderRepo : serviceProvidersList
            deactivate serviceProviderRepo
            ctrl --> ui : listOfServiceProviders
        deactivate ctrl
        ui --> Refugee : displays list of service providers offering the desired service in the specified location
    deactivate ui
deactivate Refugee

@enduml