export const MockServiceProviders = {
    serviceProvider1: {
        id: -1,
        firstName: "Maria",
        lastName: "Silva",
        email: "maria.silva@example.com",
        gender: "Female",
        phone: "+351912345678",
        photoURL: "",
        mainLanguage: "Portuguese",
        secondLanguage: "English",
        nif: "123456789",
        paymentInfoId: "987654321",
        invoiceInfoId: "654321987",
        licenseNumber: "ABC123",
        categoryId: "123",
        servicesIds: ["service1", "service2"],
        reviewIds: ["review1", "review2"],
        reviewAverage: 4.5,
    },

    serviceProvider2: {
        id: -2,
        firstName: "Pedro",
        lastName: "García",
        email: "pedro.garcia@example.com",
        gender: "Male",
        phone: "+34678901234",
        photoURL: "",
        mainLanguage: "Spanish",
        secondLanguage: "English",
        nif: "654321987",
        paymentInfoId: "987654321",
        invoiceInfoId: "456789123",
        licenseNumber: "GHI789",
        categoryId: "123",
        servicesIds: ["service7", "service8"],
        reviewIds: ["review7", "review8"],
        reviewAverage: 4.6,
    },

    serviceProvider3: {
        id: -3,
        firstName: "Anna",
        lastName: "Schmidt",
        email: "anna.schmidt@example.com",
        gender: "Female",
        phone: "+491234567890",
        photoURL: "",
        mainLanguage: "German",
        secondLanguage: "English",
        nif: "987654321",
        paymentInfoId: "123456789",
        invoiceInfoId: "789123456",
        licenseNumber: "JKL123",
        categoryId: "456",
        servicesIds: ["service9", "service10"],
        reviewIds: ["review9", "review10"],
        reviewAverage: 4.3,
    }
};
