@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title UC010 - User asks a question to Administrator

class Contact {
   id
   contactName
   contactEmail: string,
   contactDescription: string,
}

@enduml