@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title UC09 - Display a FAQ page

class Contact {
   id
   contactName
   contactEmail: string,
   contactDescription: string,
}

class HealthService {
    id
    description
    category
}

ServiceProvider "1   " - "   *" HealthService : views >

@enduml