
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (SD) - US013 - Service Provider checks his reviews

autonumber

actor ServiceProvider
participant ":ServiceProviderReviewsUI" as ui
participant ":ServiceProviderReviewsController" as ctrl
participant Repositories
participant "reviewRepo : reviewRepository" as reviewRepo


activate ServiceProvider
    ServiceProvider -> ui : starts the process of requesting reviews.
    activate ui
        ui --> ServiceProvider : requests data (service provider id).
    deactivate ui
    ServiceProvider -> ui : fills request data (service provider id)
    activate ui
        ui -> ctrl : getReviewByServiceProviderId(id)
        activate ctrl
            ctrl -> Repositories : getReviewsRepository()
                activate Repositories
                    Repositories -> Repositories : reviewsRepo()
                    Repositories --> ctrl : reviewRepo
                deactivate Repositories
            ctrl -> reviewRepo : getReviewByServiceProviderId(id)
                activate reviewRepo
                reviewRepo -> reviewRepo : getReviewByServiceProviderId(id)
                reviewRepo --> ctrl : reviewsList
                deactivate reviewRepo
            ctrl --> ui : reviewsList
            deactivate ctrl
        ui --> ServiceProvider : displays list of all service provider reviews
    deactivate ui
deactivate ServiceProvider

@enduml