@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US018 - Refugee cancels or reschedules an appointment



autonumber

actor Refugee as refugee
participant ":System" as system

activate refugee
    refugee -> system : starts the process of canceling or rescheduling the appointment
    activate system
             system --> refugee : requests data (refugee id)
             refugee -> system : fills the requested data
             system --> refugee : shows appointments list
             refugee -> system : selects appointment to cancel
             system --> refugee : shows appointment with canceled status and finishes the process
             deactivate system
deactivate refugee


@enduml