@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title UC12 - Service Provider registers date and time for scheduling

class ServiceProvider {
    id
    firstName
    lastName
    email
    gender
    photoURL
    mainLanguage
    mainPhoneNumber
    licenseNumber
    categoryId
}

class Availability {
    id
    serviceProviderId
    startDate
    endDate
    startTime
    endTime
    status
}


ServiceProvider "1   " - "   *" Availability : registers a >


@enduml