@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US016 - Administrator displays the donation report

autonumber

actor UserSystem
participant ":System" as System

activate UserSystem
    UserSystem -> System : request home page
    activate System
        System --> UserSystem : displays donation amount, total donors and appointments registered
    deactivate System

    UserSystem -> System : produces some action that implies in updates report (donations, appointments)
    activate System
        System --> UserSystem : updates data and displays in home page
    deactivate System
deactivate UserSystem

@enduml