@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UC019 - Donor views a list of donations


autonumber

actor Donor as donor
participant ":System" as system

activate donor
    donor -> system : starts the process of requesting the donation's list
    activate system
        system --> donor : displays the list
    deactivate system
deactivate donor


@enduml