@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UC07 - Refugee evaluates service provider
autonumber

actor Refugee

participant "ReviewUI" as ui
participant "ReviewController" as ctrl
participant "Repositories"
participant Repositories as repo
participant "reviewRepo : ReviewRepo" as reviewRepo

activate Refugee
    Refugee -> ui : starts the process of creating a review
    activate ui
        ui -> ctrl** : create()
        ui -> ctrl : createReview()
        activate ctrl
            ctrl -> Repositories : getReviewRepository()
                    activate Repositories
                        Repositories -> Repositories : reviewRepository()
                        Repositories-->ctrl : reviewRepo
                    deactivate Repositories
        deactivate ctrl
        ui -> Refugee : Shows the request data (appointmentId, rating (1-5), description)
        Refugee -> ui : Fills the requested data (appointmentId, rating (1-5), description)
        ui -> ctrl : createReview(appointmentId, rating, description)
        activate ctrl
        activate reviewRepo
                reviewRepo -> reviewRepo : localValidation(appointmentId, rating (1-5), description)
                reviewRepo --> reviewRepo : review
        deactivate reviewRepo

        ctrl --> ui : success
        deactivate ctrl
        ui --> Refugee : shows confirmation message
    deactivate ui
deactivate Refugee


@enduml