@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US018 - Refugee cancels or reschedules an appointment

autonumber

actor Refugee as refugee
participant ":CancelOrRescheduleUI" as ui
participant ":CancelOrRescheduleController" as ctrl
participant Repositories as repo
participant "appointmentRepo : AppointmentRepo" as appRepo
participant "appointment : Appointment" as app

activate refugee
    refugee -> ui : starts the process of canceling/rescheduling an appointment
    activate ui
        ui --> refugee : requests data(refugee id)
    deactivate ui
    refugee -> ui : fills requested data
    activate ui
        ui -> ctrl : getAppointmentsRepo( )
        activate ctrl
            ctrl -> repo : getAppointmentsRepo( )
            activate repo
                repo -> repo : appointmentRepo( )
                repo --> ctrl : appointmentRepo
            deactivate repo
            ctrl -> appRepo : getAllAppointmentsByDRefugeeId(id)
            activate appRepo
                appRepo -> appRepo : getAllAppointmentsByDate(date)
                appRepo --> ctrl : appointmentList
            deactivate appRepo
            ctrl --> ui : appointmentList
        deactivate ctrl
        ui --> refugee : shows appointments list
    deactivate ui
    refugee -> ui : chooses an appointment to cancel
    activate ui
        ui -> ctrl : getAppointmentById(id)
        activate ctrl
            ctrl -> appRepo : getAppointmentById(id)
            activate appRepo
                appRepo -> appRepo : getAppointmentById(id)
                appRepo --> ctrl : appointment
            deactivate appRepo
            ctrl -> appRepo : updateStatus(canceled)
            activate appRepo
                appRepo -> app** : updateStatus( )
                activate app
                    app -> app : updateStatus( )
                    app --> appRepo : updatedAppointment
                deactivate app
                appRepo --> ctrl : updatedAppointment
            deactivate appRepo
            ctrl --> ui : updatedAppointment
        deactivate ctrl
         ui --> refugee : displays appointment with canceled status
    deactivate ui
deactivate refugee

@enduml